# This is an example configuration file for Dependabot to update npm packages.
# For more information on configuration options, see the Dependabot docs:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2

# Define your dependencies as a list of updates
updates:
  # Example configuration for updating npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Only update minor and patch versions of dependencies
    # (i.e. keep major version constant)
    version: "w"
